### ISSUE TITLE
ArrayIndexOutOfBoundsException when categorising classes 

### ISSUE THREAD

**Issue by CristianPupazan** [schauder/degraph#66]
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at de.schauderhaft.degraph.slicer.InternalClassCategorizer$.apply(InternalClassCategorizer.scala:13)
	at de.schauderhaft.degraph.slicer.InternalClassCategorizer$.apply(InternalClassCategorizer.scala:9)
	at de.schauderhaft.degraph.slicer.MultiCategorizer$.de$schauderhaft$degraph$slicer$MultiCategorizer$$next(MultiCategorizer.scala:18)
	at de.schauderhaft.degraph.slicer.MultiCategorizer$$anonfun$combine$1.apply(MultiCategorizer.scala:11)
	at de.schauderhaft.degraph.slicer.MultiCategorizer$$anonfun$combine$1.apply(MultiCategorizer.scala:10)
	at de.schauderhaft.degraph.graph.Graph.unfilteredAdd(Graph.scala:62)
	at de.schauderhaft.degraph.graph.Graph.add(Graph.scala:59)
	at de.schauderhaft.degraph.graph.Graph.connect(Graph.scala:74)
	at de.schauderhaft.degraph.analysis.asm.GraphBuildingClassVisitor$$anonfun$visit$1.apply(GraphBuildingClassVisitor.scala:71)
	at de.schauderhaft.degraph.analysis.asm.GraphBuildingClassVisitor$$anonfun$visit$1.apply(GraphBuildingClassVisitor.scala:71)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at de.schauderhaft.degraph.analysis.asm.GraphBuildingClassVisitor.visit(GraphBuildingClassVisitor.scala:71)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.de$schauderhaft$degraph$analysis$asm$Analyzer$$analyze$1(Analyzer.scala:26)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:36)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:35)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:35)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:32)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.analyze(Analyzer.scala:32)
	at de.schauderhaft.degraph.configuration.Configuration.createGraph(Configuration.scala:31)
	at de.schauderhaft.degraph.app.Degraph$.main(Degraph.scala:23)
	at de.schauderhaft.degraph.app.Degraph.main(Degraph.scala)`

**Comment by schauder** [comment]
Can you provide some hints, how to reproduce this?

You seem to use the command line version, can you provide the configuration file / actual command line used?

**Comment by CristianPupazan** [comment]
Can the SimpleNode name be "$" or "$$" or something like that ?
```
scala> "$".split("""\$""")(0)
java.lang.ArrayIndexOutOfBoundsException: 0

scala> "$$".split("""\$""")(0)
java.lang.ArrayIndexOutOfBoundsException: 0
```

Not sure how usefull this will be but my conf file looks something like this:

```
output = myGraph.graphml
classpath = /mypath/my.jar
exclude = java*.**
exclude = scala.**
exclude = org.scalatest.**
part = {
    net.myorg.*.(*).**
}
lib = {
	net.myorg.(*).**
	*.(*).**
}
internalExternal = {
   internal net.myorg.**
   external **
}
```

The command I used:

`./degraph -f myconf.config`

**Comment by schauder** [comment]
> Can the SimpleNode name be "$" or "$$" or something like that ?

Only if you have a class with that name.

**Comment by CristianPupazan** [comment]
I managed to run this from intelij but could not reproduce it. It only happens with the command line tool.

**Comment by schauder** [comment]
Did you use the source code from master for reproducing it in intelliJ? or the jar file from the distribution you use?

**Comment by CristianPupazan** [comment]
I used master.

**Comment by schauder** [comment]
can you retry using the jar from the distribution? What distribution do you use anyway? 0.1.2 I assume?

**Comment by CristianPupazan** [comment]
I used 0.1.2. Can't seem to be able to reproduce it no more. My jar is probably different now. I will close this. Thank you !

**Comment by schauder** [comment]
If you have any idea, about what changed, since this probably means there still is a bug lurking somewhere?

Anyway, will close since it is not reproducable for now.
