### ISSUE TITLE
java.lang.IllegalArgumentException during testing

### ISSUE THREAD

**Issue by FrVaBe** [schauder/degraph#82]
I have a Spring Boot project that I want to check for Dependency cycles with Degraph. I use the following Dependendencies for that:

```xml
        <dependency>
             <groupId>junit</groupId>
             <artifactId>junit</artifactId>
             <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.schauderhaft.degraph</groupId>
            <artifactId>degraph-check</artifactId>
            <version>0.1.4</version>
            <scope>test</scope>
        </dependency>
```

When I run the simple test:

```java
    @Test
    public void allPackagesCheck() {
        assertThat(classpath().including("foo.bar.**"), is(violationFree()));
    }
```

I get the following error.

```
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.de$schauderhaft$degraph$analysis$asm$Analyzer$$analyze$1(Analyzer.scala:40)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:51)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:50)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:50)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:47)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.analyze(Analyzer.scala:47)
	at de.schauderhaft.degraph.configuration.Configuration.createGraph(Configuration.scala:26)
	at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:56)
	at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:53)
	at de.schauderhaft.degraph.check.hamcrest.HamcrestWrapper.matchesSafely(HamcrestWrapper.scala:8)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.core.Is.matches(Is.java:27)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at foo.bar.PackageDependenciesTest.allPackagesCheck(PackageDependenciesTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Not sure if this really is a Degraph error (as Depgraph runs smooth in a simple demo project). Maybe it is caused by classpath issues. As the test classes also are located in packages that are fetched up by the _including_ I wonder if this could cause the problem.

I wonder if the test classes are also taken into account when Degraphs analyses the dependencies (which I would expect because the casspath fits)? Is there any way to exclude the test classes form the analysis?

**Comment by schauder** [comment]
I think I have seen this before, this is due to a "wrong" asm version in the classpath.

Easiest way around it: move the degraph test into a separate module where you can ensure you have the correct asm version available

**Comment by FrVaBe** [comment]
Thanks for the hint. Just for reference, my project uses asm:5.0.4 wheras Degraph uses 5.1.

Moving Degraph tests to a sparate model would also eliminate the test code from the analysis. I guess there is no other option to do this?

**Comment by FrVaBe** [comment]
Error does not occure when running tests in a separate module as recommended. 

Nevertheless would be good to know if test code can be excluded from the analysis (package exclude does not work in this case) to support business and test code of a component in one module.

**Comment by schauder** [comment]
you could build a test-jar of your module under test and analyze that with Degraph.

**Comment by FrVaBe** [comment]
Not sure if I understand you correct. What I normally (without the asm incompatibility) would like to do is

- add a Degraph test to the unit tests of my model (no extra model)
- analyze the module code (without considering the test code)

My test classes are normally located in the same package as the classes under test. Thus I think Degraph will also take them into account during analyzes. But that would be wrong.

I think you mentiond that the JUnit team is also using Degraph. I will have a look how they integrated Degraph in the test code. 

Thanks!

**Comment by schauder** [comment]
Ah, I tried to solve the opposite problem.

Yes, the default setup of Degraph tests will analyze tests together with the rest. I personally consider that the correct thing to do :-) 

What you can do is change the classpath configuration that Degraph is going to analyze:

    classpath().filterClasspath("*/classes/*")...

You can pass a pattern with '*' as a wildcard and only those classpath elements that match the pattern will get analyzed. 

There is also a version that takes a function String -> Bool for more complex filters, but I don't know if you can call that from Java (it's a Scala Function).
